### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by CSer-Tang-hao** [leesb7426/CVPR2022-Task-Discrepancy-Maximization-for-Fine-grained-Few-Shot-Classification#1]

**Comment by leesb7426** [comment]
The official version of our paper is not opened yet, maybe it will be opened on June 21~23.
After that, we will upload the link of our paper.
Thank you for your interest.

**Comment by leesb7426** [comment]
The official version of our paper is released.
So you can find it through a link on our page.
Thank you for your interest
