### ISSUE TITLE
Regarding the fourth formula

### ISSUE THREAD

**Issue by leejq666** [leesb7426/CVPR2022-Task-Discrepancy-Maximization-for-Fine-grained-Few-Shot-Classification#4]
By reading your article, the channel wise representativeness score is calculated through variance。But images often have a non Gaussian distribution, is it appropriate to use variance for measurement?

**Comment by leesb7426** [comment]
Since the mean spatial feature and each channel do not share the same features, Eq. (4) and (5) are not variances.

**Comment by leejq666** [comment]
The answer was very timely, thank you very much!
