### ISSUE TITLE
About Formula 4

### ISSUE THREAD

**Issue by leejq666** [leesb7426/CVPR2022-Task-Discrepancy-Maximization-for-Fine-grained-Few-Shot-Classification#5]
Hi! What is the meaning of the double vertical symbol in Formula 4, and can you provide an explanation? Is it a European distance?Is this value directly proportional to discrimination?

**Comment by leesb7426** [comment]
The double vertical symbol ||*|| represents the norm of a vector.
And, if the European distance means Euclidean distance, it is right.

While it cannot be said that the value solely determines the discrimination of the channel, it is clear that it is one of the main causes.

**Comment by leejq666** [comment]
Thank you very much for your reply! This is very helpful for my work!
